# Generated by Django 3.1.14 on 2022-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220526_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=30),
            preserve_default=False,
        ),
    ]
