# Generated by Django 3.1.14 on 2022-05-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
    ]
